"""Update Order Table

Revision ID: c14a9b4d33c7
Revises: 
Create Date: 2023-12-02 07:14:18.823613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c14a9b4d33c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('table_place_qty', mysql.INTEGER(display_width=11)))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
